package com.smartflow.erp.recovery;

import com.smartflow.erp.invoice.Invoice;
import com.smartflow.erp.invoice.InvoiceRepository;
import com.smartflow.erp.ai.AIClient;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.util.List;

@Service
@RequiredArgsConstructor
@Slf4j
public class RecoveryService {

    private final RecoveryCaseRepository recoveryCaseRepository;
    private final InvoiceRepository invoiceRepository;
    private final AIClient aiClient;

    /**
     * Scans for overdue invoices without an active recovery case and creates them.
     * Runs daily at midnight.
     */
    @Scheduled(cron = "0 0 0 * * *")
    @Transactional
    public void autoGenerateRecoveryCases() {
        log.info("Starting automated recovery case generation...");
        
        List<Invoice> overdueInvoices = invoiceRepository.findByStatus(Invoice.Status.OVERDUE);
        
        for (Invoice invoice : overdueInvoices) {
            if (recoveryCaseRepository.findByInvoiceId(invoice.getId()).isEmpty()) {
                createCase(invoice);
            }
        }
    }

    @Transactional
    public RecoveryCase createCase(Long invoiceId) {
        Invoice invoice = invoiceRepository.findById(invoiceId)
                .orElseThrow(() -> new RuntimeException("Invoice not found"));
        return createCase(invoice);
    }

    @Transactional
    public RecoveryCase createCase(Invoice invoice) {
        // Calculate risk score using the FastAPI AI microservice
        Double riskFactor = aiClient.getInvoiceRisk(invoice);
        int riskScore = (int) (riskFactor * 100);

        RecoveryCase recoveryCase = RecoveryCase.builder()
                .invoice(invoice)
                .riskScore(riskScore)
                .status(RecoveryCase.RecoveryStatus.PENDING)
                .notes("Automatically generated by AI Debt Recovery Engine.")
                .build();

        return recoveryCaseRepository.save(recoveryCase);
    }

    public List<RecoveryCase> getAllCases() {
        return recoveryCaseRepository.findAll();
    }
}
