spring:
  application:
    name: "smartflow-erp"
  
  # Primary Database (Neon)
  datasource:
    url: ${DB_URL:jdbc:postgresql://ep-flat-rain-a4n7febx-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require}
    username: ${DB_USER:neondb_owner}
    password: ${DB_PASSWORD:npg_xlMSFzL3THY8}
    driver-class-name: org.postgresql.Driver
  
  # Secondary Database (Turso / Backup)
  secondary:
    datasource:
      url: ${SECONDARY_DB_URL:jdbc:libsql://smartflow-erp-oseemanzi.aws-us-east-1.turso.io?authToken=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NzY4MDA4NTcsImlkIjoiMDE5ZGIxOGUtY2YwMS03Yjc1LTliMDgtNTU4MDcxN2E4YjMyIiwicmlkIjoiODdkN2ZmMGYtODU0MS00MzRmLWFmOTYtNDRlYjBlODFlNTdmIn0.GTNf17aj4qBa_Ww2TrL3XDrBgLs30L2Z0Puj0naFVToI3YtxIZU8HndSBOOrIy_Lg9yeLZtOFGHrtlzyv2AKCA}
      token: ${TURSO_TOKEN:eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3NzY4MDA4NTcsImlkIjoiMDE5ZGIxOGUtY2YwMS03Yjc1LTliMDgtNTU4MDcxN2E4YjMyIiwicmlkIjoiODdkN2ZmMGYtODU0MS00MzRmLWFmOTYtNDRlYjBlODFlNTdmIn0.GTNf17aj4qBa_Ww2TrL3XDrBgLs30L2Z0Puj0naFVToI3YtxIZU8HndSBOOrIy_Lg9yeLZtOFGHrtlzyv2AKCA}
      driver-class-name: org.libsql.jdbc.LibsqlDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Sentry Configuration
sentry:
  dsn: https://abe18835734883b628093bdff0bd20b9@o4511258416447488.ingest.de.sentry.io/4511259731099728
  send-default-pii: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:4eb53509b5ce4398bc360ac511736412f83737bffe83a54b321151bd4c845bc2}
  expiration: 86400000 # 24 hours in milliseconds
